Lint/ShadowingOuterLocalVariable:
  Enabled: true

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: true

# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: true

Metrics/AbcSize:
  Max: 36

Metrics/CyclomaticComplexity:
  Max: 7

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 98

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 34

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
Style/BlockDelimiters:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: true

# Configuration parameters: Keywords.
Style/CommentAnnotation:
  Enabled: true

# Cop supports --auto-correct.
Style/DefWithParentheses:
  Enabled: true

Style/Documentation:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: true

# Configuration parameters: Exclude.
Style/FileName:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FirstParameterIndentation:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: true

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: true

# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: true

# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodName:
  Enabled: true

# Cop supports --auto-correct.
Style/NegatedIf:
  Enabled: true

# Cop supports --auto-correct.
Style/NilComparison:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: true

# Configuration parameters: SupportedStyles.
Style/RaiseArgs:
  EnforcedStyle: compact

# Cop supports --auto-correct.
Style/RedundantBegin:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterColon:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: MultiSpaceAllowedForOperators.
Style/SpaceAroundOperators:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: true

# Cop supports --auto-correct.
Style/Tab:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingComma:
  Enabled: true

# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/VariableName:
  Enabled: true
